version: '3.8'
services:
  pdflatex-api:
    build:
      context: .
    ports:
      - "9067:5000" # Host:Container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./temp_data:/app/temp_data # NEW: Bind mount host's ./temp_data to container's /container_temp_data
    environment: # NEW: Pass host path as environment variable
      HOST_TEMP_DIR: ./temp_data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/docs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s